import React, { useState, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, Apple, Code } from 'lucide-react';
import { showSuccess, showError } from '@/utils/toast';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'; // ADDED IMPORTS

interface LocalScriptGeneratorProps {
  generatedName: string | null;
  isCompleted: boolean;
}

// Hardcoded paths from the user's script
const VOLUME_NAME = "Moon Prism";
const MOUNT_PATH = "smb://192.168.1.102";
const BASE_PATH = "/Volumes/Moon Prism/DBP/Creation";
const LOGIC_TEMPLATE = "Piano Template.logicx";
const SIBELIUS_TEMPLATE = "#TEMPLATE.sib";

const generateAppleScript = (compositionName: string): string => {
  // Clean the composition name for use in file paths
  const cleanName = compositionName
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, ' '); // Keep spaces for AppleScript input

  return `
-- This script was generated by the Composition & Analysis Hub.
-- It automates the creation of your local project folder and copies templates.

-- Define volume and paths
set volumeName to "${VOLUME_NAME}"
set mountPath to "${MOUNT_PATH}"
set basePath to "${BASE_PATH}"
set logicTemplate to basePath & "/${LOGIC_TEMPLATE}"
set sibTemplate to basePath & "/${SIBELIUS_TEMPLATE}"

-- Use the generated name from the web app
set userInput to "${cleanName}"

-- Get current date in YYYYMMDD
set currentDate to do shell script "date +%Y%m%d"

-- Build folder and file names
set finalFolderName to currentDate & " " & userInput
set finalFolderPath to basePath & "/" & finalFolderName
set finalLogicxPath to finalFolderPath & "/" & finalFolderName & ".logicx"
set finalSibPath to finalFolderPath & "/" & finalFolderName & ".sib"

-- Check if volume is mounted
set volumeMounted to false
tell application "Finder"
	set mountedVolumes to name of every disk
	if mountedVolumes contains volumeName then set volumeMounted to true
end tell

-- Mount if not mounted
if volumeMounted is false then
	try
		mount volume mountPath
	on error errMsg
		display dialog "Failed to mount volume: " & errMsg
		return
	end try
end if

-- Wait for base path to appear
set folderExists to false
repeat with i from 1 to 15
	if (do shell script "test -d " & quoted form of basePath & " && echo exists || echo missing") is "exists" then
		set folderExists to true
		exit repeat
	end if
	delay 1
end repeat
if folderExists is false then
	display dialog "Base folder did not appear: " & basePath
	return
end if

-- Create the new folder
do shell script "mkdir -p " & quoted form of finalFolderPath

-- Copy and rename the Logic project
do shell script "cp -R " & quoted form of logicTemplate & " " & quoted form of finalLogicxPath

-- Copy and rename the Sibelius file
do shell script "cp " & quoted form of sibTemplate & " " & quoted form of finalSibPath

-- Open the new folder in Finder
tell application "Finder"
	open (POSIX file finalFolderPath as alias)
	activate
end tell

-- Ask user which files to open (checkbox-style)
set optionsList to {"Logic", "Sibelius", "Open none"}
set selectedOptions to (choose from list optionsList with prompt "Open which files?" default items {"Logic", "Sibelius"} with multiple selections allowed)

-- Handle user choice
if selectedOptions is false then
	return -- user cancelled the dialog
else if "Open none" is in selectedOptions then
	return -- user explicitly chose to open none
end if

-- Conditionally open selected files
if "Logic" is in selectedOptions then
	do shell script "open " & quoted form of finalLogicxPath
end if
if "Sibelius" is in selectedOptions then
	do shell script "open " & quoted form of finalSibPath
end if
`;
};

const LocalScriptGenerator: React.FC<LocalScriptGeneratorProps> = ({ generatedName, isCompleted }) => {
  const [scriptContent, setScriptContent] = useState('');

  React.useEffect(() => {
    if (generatedName) {
      setScriptContent(generateAppleScript(generatedName));
    }
  }, [generatedName]);

  const handleDownload = useCallback(() => {
    if (!scriptContent) {
      showError("Script content is empty. Please ensure the composition has a generated name.");
      return;
    }

    const blob = new Blob([scriptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    
    const cleanFileName = generatedName?.replace(/[^a-zA-Z0-9\s-]/g, '').trim().replace(/\s+/g, '_') || 'Composition_Setup';
    
    link.href = url;
    link.download = `${cleanFileName}_Setup.scpt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    showSuccess("AppleScript downloaded! Run it on your Mac to set up the project folder.");
  }, [scriptContent, generatedName]);

  const compositionName = generatedName || 'Untitled Composition';

  if (!isCompleted) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center text-xl">
            <Apple className="w-5 h-5 mr-2 text-gray-500" /> Local Project Setup Script
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">
            The script generator will be available once AI analysis is complete and the composition has a generated name.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center text-xl">
          <Apple className="w-5 h-5 mr-2 text-blue-500" /> Local Project Setup Script
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm text-muted-foreground">
          Download this custom AppleScript (`.scpt`) file to automatically mount your network drive, create the dated folder, and copy your Logic and Sibelius templates for **{compositionName}**.
        </p>
        
        <Button 
          onClick={handleDownload} 
          className="w-full bg-blue-600 hover:bg-blue-700 dark:bg-blue-700 dark:hover:bg-blue-800"
        >
          <Download className="h-4 w-4 mr-2" /> Download Project Setup Script
        </Button>

        <Collapsible>
            <CollapsibleTrigger asChild>
                <Button variant="link" className="p-0 h-auto text-sm text-muted-foreground hover:text-primary">
                    <Code className="w-4 h-4 mr-2" /> View Script Content
                </Button>
            </CollapsibleTrigger>
            <CollapsibleContent className="pt-2">
                <Label className="text-xs text-muted-foreground">AppleScript Content:</Label>
                <Textarea 
                    value={scriptContent} 
                    readOnly 
                    rows={10} 
                    className="font-mono text-xs bg-gray-50 dark:bg-gray-900"
                />
            </CollapsibleContent>
        </Collapsible>
      </CardContent>
    </Card>
  );
};

export default LocalScriptGenerator;