// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = "https://rqesjpnhrjdjnrzdhzgw.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZXNqcG5ocmpkam5yemRoZ3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMzgwNzgsImV4cCI6MjA3NzYxNDA3OH0.NqFKBFI-l96hWOGNc8QxuQdaGKVmvzw6LDGO_MsIoQc";

// Export createClient for use in SessionContextProvider
export { createClient } from '@supabase/supabase-js';

/**
 * Generates the public URL for a file in the 'piano_improvisations' bucket.
 * @param storagePath The path within the bucket (e.g., 'user_id/timestamp.m4a').
 * @returns The full public URL string.
 */
export const getPublicAudioUrl = (storagePath: string): string => {
    // Use the client method for robustness, which handles URL encoding and base path construction.
    // NOTE: This function will now need the supabase client passed to it, or it will use the anon client.
    // For public URLs, the anon client is usually sufficient.
    const anonSupabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
    const { data } = anonSupabase.storage.from('piano_improvisations').getPublicUrl(storagePath);
    return data.publicUrl;
};

/**
 * Generates the public URL for a file in the 'artwork' bucket.
 * @param storagePath The path within the bucket (e.g., 'improvisation_id/artwork_timestamp.jpg').
 * @returns The full public URL string.
 */
export const getPublicArtworkUrl = (storagePath: string): string => {
    // NOTE: This function will now need the supabase client passed to it, or it will use the anon client.
    const anonSupabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
    const { data } = anonSupabase.storage.from('artwork').getPublicUrl(storagePath);
    return data.publicUrl;
};